name-template: 'Release v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 🚀 Features
    labels:
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 🐛 Documentation
    labels:
      - documentation
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## What's Changed
  $CHANGES


version-resolver:
  major:
    labels:
      - "breaking-change"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "bugfix"
      - "chore"
  default: patch
