version: '3.8'

services:
  app:
    build: ./node_server
    container_name: app_container
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME
      # DATABASE_URL: postgresql://testuser:testpassword@db:5432/testdb

  db:
    image: postgres:latest
    container_name: db_container
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    volumes:
      - ./node_server/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready -U testuser", "-d", "testdb"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  nginx:
    build: ./nginx/
    ports:
      - 8080:80
    depends_on:
      - app