server {
    listen      *:80;
    server_name sup.localhost;


    location / {
        return 200 'Sup Hello, World!';
        add_header Content-Type text/plain;
    }

    location /bye {
        return 200 'Sup Bye!';
        add_header Content-Type text/plain;
    }

}