events {}
http {
    server {
        listen 80 default_server;
        server_name localhost bgovi-main.lan;

        # docker run --name nginx-test -p 80:80 -v /home/bgovi/Projects/Workspace/nginx_test/nginx/nginx.conf:/etc/nginx/nginx.conf:ro -v /home/bgovi/Projects/Workspace/nginx_test/nginx/hosts:/etc/hosts:ro -d nginx:alpine
        # docker exec nginx-test nginx -s reload
    

        location / {
            return 200 'Hello, World!';
            add_header Content-Type text/plain;
        }

        location /greet {
            return 200 'Hello, Welcome to /greet!';
            add_header Content-Type text/plain;
        }

        location /sup {
            return 200 'SUP';
            add_header Content-Type text/plain;
        }

    }

    server {
        listen      *:80;
        server_name foo.localhost foo.bgovi-main.lan;

        return 200 "Hello from foo.co";
    }

    server {
        listen      *:80;
        server_name bar.localhost bar.bgovi-main.lan;

        return 200 "Hello from bar.co";
    }
}
