server {
    listen      *:80;
    server_name ruth.localhost;


    location / {
        return 200 'Ruth!';
        add_header Content-Type text/plain;
    }

    location /bye {
        return 200 'BYEEE!';
        add_header Content-Type text/plain;
    }

}