name: 'Manual Workflow Test'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      debug_mode:
        description: 'Enable debug mode'
        required: false
        default: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Debug Mode: ${{ github.event.inputs.debug_mode }}"
          echo "SUP"
      - name: Echo secrets
        run: |
          echo "The first secret is below"
          echo "{{ secrets.XKEY }}"