name: MergeTest

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: |
          echo "hi"
          exit 1
      - name: Bye
        run: |
          echo "bye"